/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dasha Klyusova (https://sketchfab.com/AnoFail)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hollow-knight-5a76d93e39984f829abd6f406562265b
Title: Hollow Knight
*/

import React, { useRef, useEffect } from 'react'   
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

import hollow_knight from '/assets/3d/hollow_knight.glb'
import { a } from '@react-spring/three'

const Hollowknight = (props) => {
    const hollowKnightRef = useRef()
    const { nodes, materials } = useGLTF(hollow_knight)
    
    useEffect(() => {
      // Ensure materials render on top
      Object.values(materials).forEach(material => {
        material.depthTest = true
        material.depthWrite = true
      })
    }, [materials])

    return (
    <a.group ref={hollowKnightRef} {...props} >
      <a.group rotation={[-Math.PI / 2, 0, 0]} scale={0.068}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['Null']}
          renderOrder={999}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials['None.001']}
          renderOrder={999}
        />
      </a.group>
    </a.group>
  )
}

export default Hollowknight;